[TOKENS]
bot = ''
backend = ''

[DATABASE]
dsn = 'postgres://user:password@localhost:5432/database'

# 50 = CRITICAL
# 40 = ERROR
# 30 = WARNING
# 20 = INFO
# 10 = DEBUG
[LOGGING]
level = 20

[SERVER]
port = 2750
debug = true

[BOT]
view = 0